apiVersion: batch/v1
kind: Job
metadata:
  name: jumpbox
spec:
  template:
    spec:
      containers:
      - name: jumpbox
        image: mirror.registry:5000/bragi/test/sas-jumpbox:vtest
        env:
        - name: key
          value: value
        resources:
          limits:
            memory: "0"
            cpu: "0"
      restartPolicy: Never
  backoffLimit: 4
  activeDeadlineSeconds: 7200